### ISSUE TITLE
Nice tool! Can we make it faster

### ISSUE THREAD

**Issue by benbenliu** [chenmingxiang110/tsp_solver#1]
Seems that it has some performance bottleneck. Have we considered making it faster?

**Comment by chenmingxiang110** [comment]
Thanks for the question. I am building a new solver based on Java, and will publish soon in this repo.

**Comment by chenmingxiang110** [comment]
Quick update: the solver based on java is uploaded (see ./java). This solver is at least able to be used on python 3.x. An example is also provided in the Jupiter notebook file, pls check.
